network:
  version: 2
  modems:
    cellular:
      renderer: NetworkManager
      match: {}
      dhcp4: true
      dhcp6: true
      apn: iot.melita.io
      networkmanager:
        uuid: "ce11111a-2000-4000-8000-000000000001"
        name: "cellular"
