network:
  version: 2
  wifis:
    station:
      renderer: NetworkManager
      match: {}
      dhcp4: true
      dhcp6: true
      access-points:
        "trackIT Systems Gast":
          auth:
            key-management: "psk"
            password: "BirdsAndBats"
          networkmanager:
            uuid: "57a71000-5000-4000-8000-000000000001"
            name: "station"
            passthrough:
              connection.autoconnect: "false"
              wifi-security.auth-alg: "open"
              ipv6.addr-gen-mode: "default"
              ipv6.ip6-privacy: "-1"
      networkmanager:
        uuid: "57a71000-5000-4000-8000-000000000001"
        name: "station"
