network:
  version: 2
  ethernets:
    lan:
      renderer: NetworkManager
      match:
        name: "eth0"
      dhcp4: true
      dhcp6: true
      wakeonlan: true
      networkmanager:
        uuid: "1a111a11-4000-4000-8000-000000000001"
        name: "lan"
